---
- name: Perforce Server
  hosts: all

  roles:
    - git
    - python-pip3
    - pexpect
    - perforce

  vars_prompt:
      - name: "admin_name"
        prompt: "Set your perforce admin name"
        private: no
      - name: "admin_pass"
        prompt: "Set your perforce admin password"
        private: yes
        confirm: yes